[package]
name = "originalife-season4-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
futures-util = "0.3.30"
indicatif = "0.17.8"
octocrab = "0.39.0"
reqwest = "0.12.7"
sha2 = "0.10.8"
tokio = { version = "1.40.0", features = ["full"] }
zip = "2.2.0"
